--local files = require "config.telescope.find_files"
-- local git = require "wb.telescope.git"

-- THESE ARE OLD
-----@param lhs string
-----@param rhs string|fun()
--local function map_uwu(lhs, rhs)
--    for _, keymap in pairs { "<C-p>" .. lhs, "<C-p>" .. "<C-" .. lhs .. ">" } do
--        vim.keymap.set("n", keymap, rhs)
--    end
--end
--
--local function keymaps()
--    map_uwu("r", "<cmd>Telescope resume<CR>")
--
--    map_uwu("f", files.find)
--    map_uwu(".f", function()
--        files.find { use_buffer_cwd = true }
--    end)
--    map_uwu("p", files.git_files)
--    vim.keymap.set("n", "<space>p", files.git_files)
--    map_uwu(".p", function()
--        files.git_files { use_buffer_cwd = true }
--    end)
--    map_uwu("a", files.file_browser)
--    map_uwu("l", files.current_buffer_fuzzy_find)
--    map_uwu("o", files.project)
--    map_uwu("q", files.grep)
--    map_uwu(".q", function()
--        files.grep { use_buffer_cwd = true }
--    end)
--    map_uwu("h", files.oldfiles)
--    map_uwu("b", files.buffers)
--
--    -- map_uwu("s", git.status)
--    -- map_uwu("S", git.stash)
--end

-- These are the old keymaps
--keymaps()
